# Generated by Django 6.0.3 on 2026-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_2fa_success', '2FA Login Success'), ('login_2fa_failed', '2FA Login Failed'), ('logout', 'Logout'), ('register', 'Registration'), ('email_verified', 'Email Verified'), ('otp_resent', 'OTP Resent'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_success', 'Password Reset Success'), ('password_changed', 'Password Changed'), ('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('document_uploaded', 'Document Uploaded'), ('account_locked', 'Account Locked (Too Many Attempts)'), ('suspicious_request', 'Suspicious Request Detected')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
